# Generated by Django 5.2.6 on 2025-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_partner_alter_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('placed', 'Оформлен'), ('paid', 'Оплачен')], default='cart', max_length=10),
        ),
    ]
