# Generated by Django 5.2.6 on 2025-09-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Событие')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='year',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Кондитерская Хеппи', max_length=255, verbose_name='Название компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео о компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
