# Generated by Django 5.2.6 on 2025-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_companytimeline_alter_companyinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, default='1', help_text='Текст сертификата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.TextField(blank=True, help_text='Ссылка или путь к видео (например, /media/video/promo.mp4)', null=True),
        ),
    ]
