# Generated by Django 5.2.6 on 2025-09-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_companyinfo_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='active',
        ),
    ]
