# Используем базовый образ OpenJDK (Java)
FROM openjdk:17-jdk-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем скомпилированный JAR-файл
COPY target/spring-boot-mysqldb-0.0.1-SNAPSHOT.jar app.jar

# Экспонируем порт (обычно Spring Boot использует 8080 по умолчанию)
EXPOSE 8080

# Запускаем приложение
ENTRYPOINT ["java", "-jar", "app.jar"]